DISTRO: make sure SDK_VENDROR and TARGET_VENDOR are different
This fix is mandatory for x86 build to avoid confusion around gcc preferred provider:

WARNING: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}compilerlibs (gcc-runtime) replaces original key PREFERRED_PROVIDER_virtual/x86_64-stopensdk-linux-compilerlibs (nativesdk-gcc-runtime).
WARNING: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}g++ (gcc-cross-${TARGET_ARCH}) replaces original key PREFERRED_PROVIDER_virtual/x86_64-stopensdk-linux-g++ (gcc-crosssdk-${SDK_ARCH}).
WARNING: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}gcc (gcc-cross-${TARGET_ARCH}) replaces original key PREFERRED_PROVIDER_virtual/x86_64-stopensdk-linux-gcc (gcc-crosssdk-${SDK_ARCH}).
WARNING: Variable key PREFERRED_PROVIDER_virtual/${TARGET_PREFIX}gcc-initial (gcc-cross-initial-${TARGET_ARCH}) replaces original key PREFERRED_PROVIDER_virtual/x86_64-stopensdk-linux-gcc-initial (gcc-crosssdk-initial-${SDK_ARCH}).

ERROR: Nothing PROVIDES 'virtual/x86_64-stopensdk-linux-gcc' (but <...>/linux-next.bb, <...>/packagegroup-core-boot.bb, <...>/packagegroup-base.bb, <...>/xserver-xorg_1.18.0.bb, <...>/psplash-drm.bb DEPENDS on or otherwise requires it)
ERROR: gcc-cross-x86_64 PROVIDES virtual/x86_64-stopensdk-linux-gcc but was skipped: PREFERRED_PROVIDER_virtual/x86_64-stopensdk-linux-gcc set to gcc-crosssdk-x86_64, not gcc-cross-x86_64
ERROR: gcc-cross-x86_64 PROVIDES virtual/x86_64-stopensdk-linux-gcc but was skipped: PREFERRED_PROVIDER_virtual/x86_64-stopensdk-linux-gcc set to gcc-crosssdk-x86_64, not gcc-cross-x86_64
ERROR: Required build target 'core-image-base' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-base', 'virtual/kernel', 'virtual/x86_64-stopensdk-linux-gcc']

Change-Id: Ie6a85865e52c275cc3d75d7aacd1923a57133168
Signed-off-by: Romuald JEANNE <romuald.jeanne@st.com>
Reviewed-on: https://gerrit.st.com/60355